name: '🐞 Bug report'
description: Something went awry and you'd like to tell us about it.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A fork of [codesandbox.io/twind-bug-report](https://codesandbox.io/s/yfxpx) or [stackblitz.com/twind-bug-report](https://stackblitz.com/fork/twind-bug-report-template), that reproduces the issue. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers --npmPackages "{twind,@twind/*}"`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - annoyance
        - serious, but I can work around it
        - blocking an upgrade
        - blocking all usage of Twind
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
