blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/tw-in-js/twind/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
  - name: Discord Chat
    url: https://discord.com/invite/2aP5NkszvD
    about: Ask questions and discuss with other Twind users in real time.
