name: ✨ Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels:
  - ✨ Feature Request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request this feature!

        Do you need some help?
        ======================
        The issue tracker is meant for feature requests and bug reports only. This isn't the best place for
        support or usage questions. Questions here don't have as much visibility as they do elsewhere. Before
        you ask a question, here are some resources to get help first:

        - Read [the docs](https://twind.style/docs)
        - Explore [examples](https://github.com/tw-in-js/twind/tree/next/examples#readme)
        - Ask in [Github Discussions](https://github.com/tw-in-js/twind/discussions)
        - Ask in [Discord Chat](https://discord.com/invite/2aP5NkszvD)
  - type: textarea
    id: problem
    attributes:
      label: Describe the problem
      description: Please provide a clear and concise description the problem this feature would solve. The more information you can provide here, the better.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the proposed solution
      description: Please provide a clear and concise description of what you would like to happen.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Please provide a clear and concise description of any alternative solutions or features you've considered.
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - nice to have
        - would make my life easier
        - I cannot use Twind without it
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
