name: CI

on:
  push:
    branches:
      # Push events on next branch
      - next

  pull_request:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  CI: true

jobs:
  build:
    name: 🏗️  Build on Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      hasChangesets: ${{ steps.changesets.outputs.hasChangesets }}

    strategy:
      matrix:
        node: ['18.x']
        # os: [ubuntu-20.04]
        # Maybe add those later again
        # os: [ubuntu-20.04, macos-11, windows-2022]

    steps:
      - name: 🔧  Setup
        uses: ./.github/actions/setup
        with:
          nodeVersion: ${{ matrix.node }}

      - name: 🤘  Validate packages
      - run: |
          pnpm check
          pnpm test:coverage

      - name: 🏗️  Build packages
        run: pnpm build

      - name: 📖  Coveralls
        # prevents this step from running on forks
        if: ${{ github.repository == 'tw-in-js/twind' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: build-${{ matrix.node }}
          parallel: true
          path-to-lcov: ./coverage/lcov.info

      # if a .npmrc file is found, the GitHub Action does not recreate the file.
      - name: 📝  Updating .npmrc
        # 1. prevents this step from running on forks
        # 2. only run for push events
        # 3. only run once in the matrix
        if: ${{ github.repository == 'tw-in-js/twind' && github.event_name == 'push' && matrix.node == '18.x' }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            email=release-workflow@twind.style
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🚚  Create Release Pull Request or Publish to npm
        id: changesets
        if: ${{ github.repository == 'tw-in-js/twind' && github.event_name == 'push' && matrix.node == '18.x' }}
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm release --tag latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🌎  Deploy twind.style
        if: ${{ steps.changesets.outputs.published == 'true' && github.repository == 'tw-in-js/twind' }}
        uses: ./.github/actions/publish-pages
        with:
          workingDirectory: sites/twind.style
          run: |
            pnpm typedoc
            pnpm build
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: twind-style
          directory: sites/twind.style/build
          branch: main

      - name: 🌎  Deploy twind.run
        if: ${{ steps.changesets.outputs.published == 'true' && github.repository == 'tw-in-js/twind' }}
        uses: ./.github/actions/publish-pages
        with:
          workingDirectory: sites/twind.run
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: twind-run
          directory: sites/twind.run/.svelte-kit/cloudflare
          branch: main

  coveralls:
    name: Collect Coverage
    needs: build
    runs-on: ubuntu-latest
    # prevents this step from running on forks
    if: ${{ github.repository == 'tw-in-js/twind' }}
    steps:
      - name: 📖  Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  publish-pre-releases:
    name: 🚚  Publish pre-releases
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ needs.build.outputs.published != 'true' && github.repository == 'tw-in-js/twind' }}
    permissions:
      contents: read
      pull-requests: read
      deployments: write

    steps:
      - name: 🔧  Setup
        uses: ./.github/actions/setup
        with:
          # only install dependencies for packages that are published and for the sites
          installArgs: --filter="./packages/*" --filter="@sites/*"

      - name: 🚚  Publish as pre-release (@next.<DATETIME>)
        if: ${{ github.event_name == 'push' }}
        uses: ./.github/actions/publish-prerelease
        with:
          tag: next
          template: '{tag}.{datetime}'
          hasChangesets: ${{ needs.build.outputs.hasChangesets }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚚  Publish as canary release (@canary-<commit>)
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./.github/actions/publish-prerelease
        with:
          tag: canary
          template: '{tag}-{commit}'
          hasChangesets: ${{ needs.build.outputs.hasChangesets }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      # deploy sites using the published package versions
      - name: 🌎  Deploy twind.style
        uses: ./.github/actions/publish-pages
        with:
          workingDirectory: sites/twind.style
          run: |
            pnpm typedoc
            pnpm build
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: twind-style
          directory: sites/twind.style/build
          branch: ${{ (github.event.number && format('pr-{0}', github.event.number)) || (github.event_name == 'pull_request' && 'canary') || 'next' }}

      - name: 🌎  Deploy twind.run
        uses: ./.github/actions/publish-pages
        with:
          workingDirectory: sites/twind.run
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: twind-run
          directory: sites/twind.run/.svelte-kit/cloudflare
          branch: ${{ (github.event.number && format('pr-{0}', github.event.number)) || (github.event_name == 'pull_request' && 'canary') || 'next' }}
